<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
    <EmbeddedResource Remove="Templates\**" />
    <None Remove="Templates\**" />
    <Page Remove="Templates\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AnimatedImage.Wpf" Version="2.1.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="ImoutoRebirth.ApngWpfPlayer" Version="1.4.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
    <PackageReference Include="System.Speech" Version="10.0.5" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmithForge.ChatEngine\SmithForge.ChatEngine.csproj" />
  </ItemGroup>

  <!-- Добавь эту секцию для шрифтов -->
  <ItemGroup>
    <Resource Include="Assets\Fonts\SpectralSC-Regular.ttf" />
    <Resource Include="Assets\Fonts\SpectralSC-Bold.ttf" />
    <Resource Include="Assets\Fonts\SpectralSC-Italic.ttf" />
    <Resource Include="Assets\Fonts\SpectralSC-Medium.ttf" />
    <Resource Include="Assets\Fonts\SpectralSC-SemiBold.ttf" />
    <Resource Include="Assets\Fonts\SpectralSC-Light.ttf" />
  </ItemGroup>

</Project>